version: '3.8' 
services:
  postgres:
    image: postgres:latest 
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: charlesalmeiida
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgre
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
volumes:
  postgres_data:
    driver: local
